# Generated by Django 2.1.5 on 2019-08-11 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_auto_20190811_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='Date',
            new_name='date',
        ),
    ]
